### ISSUE TITLE
Suggestion: Inventory sorting and customizable keybind

### ISSUE THREAD

**Issue by max-aider** [16underscore/Sort#1]
That's it. I really like your mod for the minimalistic approach :D

**Comment by ChrisChrome** [comment]
+1

**Comment by oOHiyoriOo** [comment]
+1

**Comment by 16underscore** [comment]
Recently, I start working on an extension mod that will allow custom keybinds. I think an extension is a great idea to not bloat the main mod too much. :D The Inventory sorting feature will become a part of the main mod in the future. [Extension mod](https://github.com/16underscore/SortExtension)
